config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'health_care_companies#index'
  resources :health_care_companies do
    resources :doctors do
      resources :hours, only: %i[create new destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  belongs_to :health_care_company
  has_many :hours, dependent: :destroy
  before_save :capitalize_name

  validates :name, presence: true, length: { minimum: 5, maximum: 40 }

  private

  def capitalize_name
    self.name = name.split.collect(&:capitalize).join(' ') if name && !name.blank?
  end
end

app/models/health_care_company.rb
class HealthCareCompany < ApplicationRecord
  has_many :doctors, dependent: :destroy
  has_many :hours, dependent: :destroy
  before_save :capitalize_name

  validates :name, presence: true, length: { minimum: 5, maximum: 40 }

  private

  def capitalize_name
    self.name = name.split.collect(&:capitalize).join(' ') if name && !name.blank?
  end
end

app/models/hour.rb
class Hour < ApplicationRecord
  belongs_to :doctor
  belongs_to :health_care_company

  validates :weekday, :opening_hour, :opening_minute, :closing_hour, :closing_minute, presence: true

  WEEKDAY = %w[Monday Tuesday Wednesday Thursday Friday Saturday Sunday]
  HOUR = (0o0..23)
  MINUTE = (0o0..59)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :find_health_care_company, only: %i[index show edit]
  before_action :find_doctor, only: %i[show destroy update edit]

  def index
    @doctors = Doctor.where(health_care_company: @health_care_company)
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    @doctor.health_care_company_id = params[:health_care_company_id]
    if @doctor.save
      redirect_to health_care_company_doctors_path
    else
      render :new
    end
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to health_care_company_doctors_path
    else
      render :edit
    end
  end

  def destroy
    redirect_to health_care_companies_path if @doctor.destroy
  end

  private

  def doctor_params
    params.require(:doctor).permit(:name)
  end

  def find_doctor
    @doctor = Doctor.find(params[:id])
  end

  def find_health_care_company
    @health_care_company = HealthCareCompany.find(params[:health_care_company_id])
  end
end

app/controllers/health_care_companies_controller.rb
class HealthCareCompaniesController < ApplicationController
  before_action :find_health_care_company, only: %i[show destroy edit update]

  def index
    @health_care_companies = HealthCareCompany.all
  end

  def new
    @health_care_company = HealthCareCompany.new
  end

  def create
    @health_care_company = HealthCareCompany.new(company_params)
    if @health_care_company.save
      redirect_to health_care_companies_path 
    else
      render :new
    end
  end

  def update
    if @health_care_company.update(company_params)
      redirect_to health_care_company_path
    else
      render :edit
    end
  end

  def destroy
    @health_care_company.destroy
    redirect_to health_care_companies_path
  end

  private

  def company_params
    params.require(:health_care_company).permit(:name)
  end

  def find_health_care_company
    @health_care_company = HealthCareCompany.find(params[:id])
  end
end

app/controllers/hours_controller.rb
class HoursController < ApplicationController
  before_action :find_hour, only: %i[destroy show]

  def index
    @hours = Hour.where(doctor: @doctor)
  end

  def new
    @hour = Hour.new
  end

  def create
    @hour = Hour.new(hour_params)
    @hour.health_care_company_id = params[:health_care_company_id]
    @hour.doctor_id = params[:doctor_id]
    if @hour.save
      redirect_to health_care_company_doctors_path
    else
      render 'new'
    end
  end

  def destroy
    @health_care_company = HealthCareCompany.find(params[:health_care_company_id])
    @doctor = Doctor.find(params[:doctor_id])
    @hour.destroy
    redirect_to health_care_company_doctor_path(@health_care_company, @doctor)
  end

  private

  def hour_params
    params.require(:hour).permit(:weekday, :opening_hour, :opening_minute, :closing_hour, :closing_minute)
  end

  def find_hour
    @hour = Hour.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/health_care_companies_helper.rb
module HealthCareCompaniesHelper
end

app/helpers/hours_helper.rb
module HoursHelper
end

app/views/doctors/edit.html.erb
<div class="doctor_form_container">

  <%= simple_form_for @doctor, url: health_care_company_doctor_path(@health_care_company, @doctor) do |f| %>
    <%= f.input :name %>
    <%= f.submit%>
  <% end %>
</div>

app/views/doctors/index.html.erb
<div>
  
  <div class="container white-bg padding shadow center-div shadow margin">
  <% if (@health_care_company.name).end_with?('s') %>
    <h1> <%= "#{@health_care_company.name}' doctors." %> </h1>
  <% else %>
    <h1> <%= "#{@health_care_company.name}'s doctors." %> </h1>
  <% end %>
  <% t= Time.now %>
  <% weekday = Date.today.strftime("%A") %>
  <%= "Today is #{weekday} the #{t.day}/#{t.month}/#{t.year}" %>
  </div>
  <% @doctors.each do |doctor| %>
    <div class="container center-div">
      <div class="doctor-info white-bg shadow padding">
        <%= "Doctor #{doctor.name}"%>
        <div>
          <%= link_to ('<i class="fas fa-wrench"></i>').html_safe, health_care_company_doctor_path(@health_care_company, doctor), method: :get ,class: "btn btn-light"%>
          <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe , health_care_company_doctor_path(@health_care_company, doctor), method: :delete ,class: "btn btn-light"%>
        </div>
      </div>
           
      <% hours = doctor.hours.all %>
      <div class="week">
        <div class="day padding white-bg shadow">
          <span class="black-bd day-header"> <%= weekday == "Monday" ? "<b>Monday</b>".html_safe : "Monday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Monday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div> 
         <div class="day padding white-bg shadow">
          <span class="black-bd day-header"><%= weekday == "Tuesday" ? "<b>Tuesday</b>".html_safe : "Tuesday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Tuesday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div>
         <div class="day padding white-bg shadow">
          <span class="black-bd day-header"> <%= weekday == "Wednesday" ? "<b>Wednesday</b>".html_safe : "Wednesday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Wednesday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div> 
         <div class="day padding white-bg shadow">
          <span class="black-bd day-header"> <%= weekday == "Thursday" ? "<b>Thursday</b>".html_safe : "Thursday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Thursday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div> 
         <div class="day padding white-bg shadow">
          <span class="black-bd day-header"> <%= weekday == "Friday" ? "<b>Friday</b>".html_safe : "Friday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Friday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div> 
         <div class="day padding white-bg shadow">
         <span class="black-bd day-header">  <%= weekday == "Saturday" ? "<b>Saturday</b>".html_safe : "Saturday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Saturday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div> 
         <div class="day padding white-bg shadow">
         <span class="black-bd day-header"> <%= weekday == "Sunday" ? "<b>Sunday</b>".html_safe : "Sunday" %></span>
          <% hours.each do |h| %>
            <% if h.weekday == "Sunday"%>
              <%= " #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
              <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, doctor, h), method: :delete,class: "delete-hour btn btn-light"  %>
            <% end %>
          <% end %>  
        </div>     
      </div>  
    </div>  
  <% end %>
  <div class="container center-div">
    <%= link_to ('<i class="fas fa-arrow-left"></i>').html_safe, health_care_companies_path, method: :get ,class: "btn btn-light"%>
    <%= link_to ('<i class="fas fa-plus-square"></i>').html_safe, new_health_care_company_doctor_path, method: :get ,class: "btn btn-light"%>  
  </div>
</div>

app/views/doctors/new.html.erb
<div class="container">
    <%= simple_form_for @doctor, url: health_care_company_doctors_path do |f| %>
      <%= f.input :name %>
      <%= f.submit "Confirm",class: "btn btn-light"%>
    <% end %>
</div>

app/views/doctors/show.html.erb
<div class="container">
  <div class="container company white-bg shadow padding">
    <%= "Doctor #{@doctor.name}" %>
    <div>
        <%= link_to ('<i class="fas fa-wrench"></i>').html_safe, edit_health_care_company_doctor_path , method: :get ,class: "btn btn-light"%>
    <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_doctor_path(@health_care_company, @doctor), method: :delete ,class: "btn btn-light"%>
    </div>
  </div>
  <% hours = @doctor.hours.all %>
  <% hours.each do |h| %> 
    <div class="container company white-bg shadow padding">
      <%= "#{h.weekday} from #{h.opening_hour.rjust(2, '0')}:#{h.opening_minute.rjust(2, '0')} to #{h.closing_hour.rjust(2, '0')}:#{h.closing_minute.rjust(2, '0')}" %>
      <%= link_to ('<i class="fas fa-trash-alt test"></i>').html_safe, health_care_company_doctor_hour_path(@health_care_company, @doctor, h), method: :delete,class: "btn btn-light"  %>
    </div>
  <% end %>
  
</div>
<div class="container hour-actions white-bg shadow">
    <%= link_to ('<i class="fas fa-arrow-left"></i>').html_safe, health_care_company_doctors_path(@health_care_company), method: :get ,class: "btn btn-light"%>
    <%= link_to ('<i class="fas fa-plus-square"></i>').html_safe, new_health_care_company_doctor_hour_path(@health_care_company, @doctor), method: :get ,class: "btn btn-light"%>
  </div>

app/views/health_care_companies/_health_care_company_form.html.erb
<div class="container">
  <%= simple_form_for @health_care_company do |f| %>
    <%= f.input :name %>
    <%= f.submit "Confirm",class: "btn btn-light" %>
  <% end %>
</div>

app/views/health_care_companies/edit.html.erb
<div class="list-container">
  <%= render "health_care_company_form" %>
</div>

app/views/health_care_companies/index.html.erb
<div class="container"><h1 class="white-bg shadow">Health care practices near you.</h1> 
<% @health_care_companies.each do |company| %>
  <div class ="container white-bg shadow company padding">
    <%= company.name %>
    <div>
       <%= link_to ('<i class="fas fa-info-circle"></i>').html_safe, health_care_company_doctors_path(company) ,class: "btn btn-light"%>
      <%= link_to ('<i class="fas fa-wrench"></i>').html_safe, health_care_company_path(company), method: :get ,class: "btn btn-light"%>
    </div>
  </div>
<% end %>
  <%= link_to ('<i class="fas fa-plus-square"></i>').html_safe, new_health_care_company_path, method: :get ,class: "btn btn-light"%>
</div>

app/views/health_care_companies/new.html.erb
  <%= render "health_care_company_form" %>

app/views/health_care_companies/show.html.erb
<div class="container">
  <div class="container white-bg shadow company">
<%= @health_care_company.name %>
  <%= link_to ('<i class="fas fa-arrow-left"></i>').html_safe, health_care_companies_path,class: "btn btn-light" %>
  <%= link_to ('<i class="fas fa-wrench"></i>').html_safe, edit_health_care_company_path(@health_care_company), method: :get,class: "btn btn-light" %>
  <%= link_to ('<i class="fas fa-trash-alt"></i>').html_safe, health_care_company_path(@health_care_company), method: :delete,class: "btn btn-light" %>
</div>
</div>

app/views/hours/new.html.erb
<div class="container">
  <h1>Add opening time</h1>
  <%= simple_form_for @hour, url: health_care_company_doctor_hours_path do |f| %>
    <%= "Weekday" %>
    <%= f.input_field :weekday , collection: Hour::WEEKDAY %>
    <%= "Starting time" %>
    <%= f.input_field :opening_hour, collection: Hour::HOUR %>
    <%= f.input_field :opening_minute, collection: Hour::MINUTE %>
 <%= "Ending time" %>
    <%= f.input_field :closing_hour, collection: Hour::HOUR %>
    <%= f.input_field :closing_minute, collection: Hour::MINUTE %>
    <%= f.submit "Add",class: "btn btn-light"  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloopApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class=" shadow white-bg navbar navbar-expand-lg navbar-light">
  <%= link_to ('<i class="fas fa-home"></i>').html_safe, root_path %>
</nav>